### ISSUE TITLE
Building as an image depends on Backend

### ISSUE THREAD

**Issue by littletuna4** [Agilo/fashion-starter#19]
**Describe the bug**
I am trying to deploy a containerised front end. The build step for the storefront is failing due to the following error:

```
 > [8/8] RUN yarn build:
#0 1.296 yarn run v1.22.19
#0 1.339 $ next build
#0 2.392 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#0 2.392 This information is used to shape Next.js' roadmap and prioritize features.
#0 2.392 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#0 2.392 https://nextjs.org/telemetry
#0 2.392 
#0 2.475   ▲ Next.js 15.0.1
#0 2.475   - Environments: .env.local, .env
#0 2.475 
#0 2.558    Creating an optimized production build ...
#0 45.90  ✓ Compiled successfully
#0 45.91    Linting and checking validity of types ...
#0 56.46    Collecting page data ...
#0 57.46 Error: Error setting up the request: fetch failed
#0 57.46     at a (/app/.next/server/chunks/492.js:1:44707)
#0 57.46     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
#0 57.46     at async Object.o [as generateStaticParams] (/app/.next/server/app/[countryCode]/(main)/about/page.js:1:2730)
#0 57.46     at async builtRouteParams (/app/node_modules/next/dist/build/utils.js:986:36)
#0 57.46     at async buildAppStaticPaths (/app/node_modules/next/dist/build/utils.js:940:25)
#0 57.46     at async /app/node_modules/next/dist/build/utils.js:1149:79
#0 57.46     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:157:20)
#0 57.46 Error: Error setting up the request: fetch failed
#0 57.46     at a (/app/.next/server/chunks/492.js:1:44707)
#0 57.46     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
#0 57.46     at async Object.m [as generateStaticParams] (/app/.next/server/app/[countryCode]/(main)/inspiration/page.js:1:5353)
#0 57.46     at async builtRouteParams (/app/node_modules/next/dist/build/utils.js:986:36)
#0 57.46     at async buildAppStaticPaths (/app/node_modules/next/dist/build/utils.js:940:25)
#0 57.46     at async /app/node_modules/next/dist/build/utils.js:1149:79
#0 57.46     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:157:20)
#0 57.46 
#0 57.46 > Build error occurred
#0 57.46 Error: Failed to collect page data for /[countryCode]/about
#0 57.46     at /app/node_modules/next/dist/build/utils.js:1233:15
#0 57.46     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
#0 57.46   type: 'Error'
#0 57.46 }
#0 57.52 error Command failed with exit code 1.
#0 57.52 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
ERROR: failed to solve: executor failed running [/bin/sh -c yarn build]: exit code: 1
```

I think this is implying that the frontend is trying to generate static pages based on the dynamic data from the backend (which isn't available from the build environment)

See commit: 48c046f04ba3621bfe199c9a888ff413c07e3bf3

Is this interpretation correct?
Regardless, has anyone experienced this and worked out a solution?

dockerfile used:

```
# Use Node.js base image
FROM node:22

RUN corepack enable
RUN corepack prepare yarn@4.3.1 --activate

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN yarn install

# Copy the rest of the app files
COPY . .

# Build the Next.js app
RUN yarn build


# Expose the port used by Next.js
EXPOSE 8000

# Start the Next.js app
CMD ["yarn", "start"]

```

**Comment by littletuna4** [comment]
Yes, the backend needs to be accessible to build the frontend with this starter.
